# Generated by Django 4.2.2 on 2023-06-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_image'),
        ('community', '0003_alter_community_logo_communitymembers'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
