# Generated by Django 4.2.2 on 2023-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email_alter_users_name_alter_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default=1, max_length=500, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
