# Generated by Django 4.2.2 on 2023-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]