# Generated by Django 4.2.2 on 2023-06-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_image'),
        ('community', '0002_community_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(default=1, max_length=500, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
